services:
  pykmip:
    network_mode: "host"
    profiles: ['pykmip']
    image: ${PYKMIP_IMAGE:-ghcr.io/scality/cloudserver/pykmip}
    build:
      context: ./pykmip
    volumes:
      - /tmp/artifacts/:/artifacts
