---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/master
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: true
          retryFetch: true
          haltOnFailure: true
      - ShellCommand:
          name: install dependencies
          command: yarn
      - ShellCommand:
          name: run lint yml
          command: yarn lint_yml --silent
      - ShellCommand:
          name: run lint
          command: yarn lint --silent --max-warnings 0
      - ShellCommand:
          name: run lint_md
          command: yarn lint_md --silent
      - ShellCommand:
          name: run test
          command: yarn test --silent
      - ShellCommand:
          name: run ft_test
          command: yarn ft_test
      - ShellCommand:
          name: run executables tests
          command: yarn && yarn test
          workdir: '%(prop:builddir)s/build/lib/executables/pensieveCreds/'
