---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/master
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: install dependencies
          command: yarn install --frozen-lockfile
      - ShellCommand:
          name: run lint yml
          command: yarn run --silent lint_yml
      - ShellCommand:
          name: run lint
          command: yarn run --silent lint -- --max-warnings 0
      - ShellCommand:
          name: run lint_md
          command: yarn run --silent lint_md
      - ShellCommand:
          name: add hostname
          command: sudo sh -c "echo '127.0.0.1 testrequestbucket.localhost' \
            >> /etc/hosts"

      - ShellCommand:
          name: run test
          command: yarn run --silent test
      - ShellCommand:
          name: run ft_test
          command: yarn run ft_test
      - ShellCommand:
          name: run executables tests
          command: yarn install && yarn test
          workdir: '%(prop:builddir)s/build/lib/executables/pensieveCreds/'
