---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: local
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: install dependencies
          command: npm install
      - ShellCommand:
          name: run lint yml
          command: npm run --silent lint_yml
      - ShellCommand:
          name: run lint
          command: npm run --silent lint -- --max-warnings 0
      - ShellCommand:
          name: run lint_md
          command: npm run --silent lint_md

      - ShellCommand:
          name: run test
          command: npm run --silent test
      - ShellCommand:
          name: run ft_test
          command: npm run ft_test
      - ShellCommand:
          name: run executables tests
          command: npm install && npm test
          workdir: '%(prop:builddir)s/build/lib/executables/pensieveCreds/'
