---
name: dependency review

on:
  pull_request:
    branches: [development/*, stabilization/*, hotfix/*]
  push:
    branches-ignore:
    - 'development/**'

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: development/8.1
          head-ref: ${{ github.ref_name }}
