---
name: tests-kmip

on:
  push:
    branches-ignore:
    - 'development/**'
    paths:
    - .github/workflows/tests-kmip.yaml
    - .github/pykmip/**
    - lib/network/kmip/**
    - tests/functional/kmip/**

jobs:
  test-kmip:
    runs-on: ubuntu-22.04
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Setup pykmip.local in etc/hosts
      shell: bash
      run: sudo echo "127.0.0.1 pykmip.local" | sudo tee -a /etc/hosts

    - name: Start docker pykmip
      run: docker compose --profile pykmip up -d
      working-directory: .github

    - name: install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      continue-on-error: true # TODO ARSN-97 Remove it when no errors in TS

    - name: run kmip ClusterClient functional tests on pykmip
      run: yarn jest tests/functional/kmip/ClusterClient.spec.js --forceExit
